# -*- coding: utf-8 -*-
"""main sql query generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ofzRKnXRHr_iwKPUoLziXi4eEdVfugmk
"""

!pip install -q gradio

import gradio as gr
import re

# Fake schema
schema = {
    "users": ["id","name","email","age","country","status"],
    "orders": ["id","user_id","product_name","amount","order_date","status"],
    "products": ["id","name","price","category","stock"],
    "transactions": ["id","user_id","amount","date","type"]
}

# table detection
def get_table(text):
    text = text.lower()

    if "user" in text:
        return "users"
    elif "order" in text:
        return "orders"
    elif "product" in text:
        return "products"
    elif "transaction" in text:
        return "transactions"
    else:
        return "users"

# SQL generator
def generate_sql(text):

    text = text.lower()
    table = get_table(text)

    sql = f"SELECT * FROM {table}"
    condition = None

    numbers = re.findall(r"\d+", text)

    # AGE conditions
    if "age" in text:
        if "greater than" in text and numbers:
            condition = f"age > {numbers[0]}"
        elif "less than" in text and numbers:
            condition = f"age < {numbers[0]}"
        elif "equal" in text and numbers:
            condition = f"age = {numbers[0]}"

    # AMOUNT conditions
    elif "amount" in text:
        if "greater than" in text and numbers:
            condition = f"amount > {numbers[0]}"
        elif "less than" in text and numbers:
            condition = f"amount < {numbers[0]}"
        elif "equal" in text and numbers:
            condition = f"amount = {numbers[0]}"

    # PRICE conditions
    elif "price" in text:
        if "greater than" in text and numbers:
            condition = f"price > {numbers[0]}"
        elif "less than" in text and numbers:
            condition = f"price < {numbers[0]}"

    if condition:
        sql += f" WHERE {condition}"

    sql += " LIMIT 10"

    return sql

# chatbot function
def chatbot(user_input):
    return generate_sql(user_input)

# UI
demo = gr.Interface(
    fn=chatbot,
    inputs="text",
    outputs="text",
    title="🔥  SQL Query Generator",
    description="Type English sentence → Get SQL query (Improved version)"
)

demo.launch(share=True)
