# -*- coding: utf-8 -*-
"""SQL Query Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RZJf0yBFMP3NYPrr42UG2rDjn0xduCb
"""

!pip install -q gradio transformers torch reportlab

import gradio as gr
import re
from reportlab.pdfgen import canvas

schema = {
    "users": ["id","name","email","signup_date","age","country","status"],
    "orders": ["id","user_id","product_name","amount","order_date","status"],
    "products": ["id","name","price","category","stock"],
    "transactions": ["id","user_id","amount","date","type"]
}

dangerous_keywords = ["drop","delete","alter","truncate","insert","update"]

def is_safe(text):
    text = text.lower()
    for word in dangerous_keywords:
        if word in text:
            return False
    return True

def get_table_name(text):

    text = text.lower()

    if "user" in text:
        return "users"

    elif "order" in text:
        return "orders"

    elif "product" in text:
        return "products"

    elif "transaction" in text:
        return "transactions"

    return "users"

def generate_sql(text):

    if not is_safe(text):
        return "Unsafe query detected!"

    table = get_table_name(text)
    text = text.lower()

    sql = f"SELECT * FROM {table}"

    if "greater than" in text:
        number = text.split("greater than")[1].strip().split()[0]
        sql += f" WHERE amount > {number}"

    sql += " LIMIT 10"

    return sql

def export_pdf(query):

    file_name = "sql_report.pdf"

    c = canvas.Canvas(file_name)
    c.drawString(100,750,"SQL Query Report")
    c.drawString(100,720,query)
    c.save()

    return file_name

def chatbot(user_input):

    sql = generate_sql(user_input)

    return sql

demo = gr.Interface(
    fn=chatbot,
    inputs="text",
    outputs="text",
    title="SQL Query Generator",
    description="Type your request in English and get SQL query"
)

demo.launch(share=True)